@startuml 可见性
' “可见性”表示该属性对类外的元素是否可见，包括
' 公有（Public）、私有（Private）、受保护（Protected）和朋友（Friendly）4 种，
' 在类图中分别用符号+、-、#、~表示。

class Flight {
    ' public
    + flightNumber : Integer
    ' private
    - flightNumber : Integer
    ' protected
    # flightNumber : Integer
    ' friendly
    ~ flightNumber : Integer
}
@enduml



@startuml 类之间的关系
- 依赖关系
- 关联关系

- 聚合关系
- 组合关系

- 泛化关系
- 实现关系
@enduml

@startuml 类之间的关系 实例
依赖 <.. Dependency
依赖 .. Dependency

关联 - Association : drives >

聚合 o-- Aggregation

组合 *-- Composition

泛化 <|-- Generalization

实现 <|.. Realization
@enduml

@startuml -
class Car

Driver - Car : drives >
Car *- Wheel : have 4 >
Car -- Person : < owns

@enduml

@startuml 注释
class Object << general >>
Object <|--- ArrayList
note top of Object : In java, every class\nextends this one.
note "This is a floating note" as N1
note "This note is connected\nto several objects." as N2
Object .. N2
N2 .. ArrayList
class Foo
note left: On last defined class
@enduml

